/*
 * This file was generated automatically by ExtUtils::ParseXS version 3.18 from the
 * contents of forks.xs. Do not edit this file, edit forks.xs instead.
 *
 *    ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "forks.xs"
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

#define NEED_PL_signals
#include "ppport.h"

#define MY_CXT_KEY "threads::shared::_guts" XS_VERSION

typedef struct {
    int dummy;          /* you can access this elsewhere as MY_CXT.dummy */
} my_cxt_t;

START_MY_CXT

/* Scope hook to determine when a locked variable should be unlocked */

void
exec_leave(pTHX_ SV *both) {
    U32 process;
    U32 ordinal;
    AV *av_ord_lock;

    dSP;
    ENTER;
    SAVETMPS;

    av_ord_lock = (AV*)SvRV(both);
    process = (U32)SvUV((SV*)*av_fetch(av_ord_lock, 1, 0));
    ordinal = (U32)SvUV((SV*)*av_fetch(av_ord_lock, 2, 0));
  /*  printf ("unlock: ordinal = %d, process = %d\n",ordinal,process); */
    SvREFCNT_dec(av_ord_lock);
    SvREFCNT_dec(both);

    PUSHMARK(SP);
    XPUSHs(sv_2mortal(newSVuv(ordinal)));
    PUTBACK;

    if (process == getpid()) {
        call_pv( "threads::shared::_unlock",G_DISCARD );
    }

    SPAGAIN;
    PUTBACK;
    FREETMPS;
    LEAVE;
}

/* Implements Perl-level share() and :shared */

void
Perl_sharedsv_share(pTHX_ SV *sv)
{
    dSP;
    switch(SvTYPE(sv)) {
/*    case SVt_PVGV:
        Perl_croak(aTHX_ "Cannot share globs yet");
        break; */

    case SVt_PVCV:
        Perl_croak(aTHX_ "Cannot share subs yet");
        break;

    default:
        ENTER;
        SAVETMPS;

        PUSHMARK(sp);
        XPUSHs(sv_2mortal(newRV_inc(sv)));
        PUTBACK;

        call_pv( "threads::shared::_share",G_DISCARD );

        SPAGAIN;
        PUTBACK;
        FREETMPS;
        LEAVE;

        break;
    }
}

/* Inititalize core Perl hooks */

void
Perl_sharedsv_init(pTHX)
{
/*    PL_lockhook = &Perl_sharedsv_locksv; */
#ifdef PL_sharehook
    PL_sharehook = &Perl_sharedsv_share;
#endif
#ifdef PL_destroyhook
/*    PL_destroyhook = &Perl_shared_object_destroy; */
#endif
}


#line 108 "forks.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef dVAR
#  define dVAR		dNOOP
#endif


/* This stuff is not part of the API! You have been warned. */
#ifndef PERL_VERSION_DECIMAL
#  define PERL_VERSION_DECIMAL(r,v,s) (r*1000000 + v*1000 + s)
#endif
#ifndef PERL_DECIMAL_VERSION
#  define PERL_DECIMAL_VERSION \
	  PERL_VERSION_DECIMAL(PERL_REVISION,PERL_VERSION,PERL_SUBVERSION)
#endif
#ifndef PERL_VERSION_GE
#  define PERL_VERSION_GE(r,v,s) \
	  (PERL_DECIMAL_VERSION >= PERL_VERSION_DECIMAL(r,v,s))
#endif
#ifndef PERL_VERSION_LE
#  define PERL_VERSION_LE(r,v,s) \
	  (PERL_DECIMAL_VERSION <= PERL_VERSION_DECIMAL(r,v,s))
#endif

/* XS_INTERNAL is the explicit static-linkage variant of the default
 * XS macro.
 *
 * XS_EXTERNAL is the same as XS_INTERNAL except it does not include
 * "STATIC", ie. it exports XSUB symbols. You probably don't want that
 * for anything but the BOOT XSUB.
 *
 * See XSUB.h in core!
 */


/* TODO: This might be compatible further back than 5.10.0. */
#if PERL_VERSION_GE(5, 10, 0) && PERL_VERSION_LE(5, 15, 1)
#  undef XS_EXTERNAL
#  undef XS_INTERNAL
#  if defined(__CYGWIN__) && defined(USE_DYNAMIC_LOADING)
#    define XS_EXTERNAL(name) __declspec(dllexport) XSPROTO(name)
#    define XS_INTERNAL(name) STATIC XSPROTO(name)
#  endif
#  if defined(__SYMBIAN32__)
#    define XS_EXTERNAL(name) EXPORT_C XSPROTO(name)
#    define XS_INTERNAL(name) EXPORT_C STATIC XSPROTO(name)
#  endif
#  ifndef XS_EXTERNAL
#    if defined(HASATTRIBUTE_UNUSED) && !defined(__cplusplus)
#      define XS_EXTERNAL(name) void name(pTHX_ CV* cv __attribute__unused__)
#      define XS_INTERNAL(name) STATIC void name(pTHX_ CV* cv __attribute__unused__)
#    else
#      ifdef __cplusplus
#        define XS_EXTERNAL(name) extern "C" XSPROTO(name)
#        define XS_INTERNAL(name) static XSPROTO(name)
#      else
#        define XS_EXTERNAL(name) XSPROTO(name)
#        define XS_INTERNAL(name) STATIC XSPROTO(name)
#      endif
#    endif
#  endif
#endif

/* perl >= 5.10.0 && perl <= 5.15.1 */


/* The XS_EXTERNAL macro is used for functions that must not be static
 * like the boot XSUB of a module. If perl didn't have an XS_EXTERNAL
 * macro defined, the best we can do is assume XS is the same.
 * Dito for XS_INTERNAL.
 */
#ifndef XS_EXTERNAL
#  define XS_EXTERNAL(name) XS(name)
#endif
#ifndef XS_INTERNAL
#  define XS_INTERNAL(name) XS(name)
#endif

/* Now, finally, after all this mess, we want an ExtUtils::ParseXS
 * internal macro that we're free to redefine for varying linkage due
 * to the EXPORT_XSUB_SYMBOLS XS keyword. This is internal, use
 * XS_EXTERNAL(name) or XS_INTERNAL(name) in your code if you need to!
 */

#undef XS_EUPXS
#if defined(PERL_EUPXS_ALWAYS_EXPORT)
#  define XS_EUPXS(name) XS_EXTERNAL(name)
#else
   /* default to internal */
#  define XS_EUPXS(name) XS_INTERNAL(name)
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)    S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage        S_croak_xs_usage
#endif

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#line 250 "forks.c"

XS_EUPXS(XS_threads__shared___DEF_PL_sharehook); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_threads__shared___DEF_PL_sharehook)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	bool	RETVAL;
#line 106 "forks.xs"
#ifdef PL_sharehook
        RETVAL = 1;
#else
        RETVAL = 0;
#endif
#line 266 "forks.c"
	ST(0) = boolSV(RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_threads__shared__check_pl_signal_unsafe_flag); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_threads__shared__check_pl_signal_unsafe_flag)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
#line 120 "forks.xs"
        U32 flags;
#line 283 "forks.c"
	bool	RETVAL;
#line 122 "forks.xs"
        flags = PL_signals & PERL_SIGNALS_UNSAFE_FLAG;
        if (flags == 0) {
            RETVAL = 0;
        } else {
            RETVAL = 1;
        }
#line 292 "forks.c"
	ST(0) = boolSV(RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_threads__shared_share); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_threads__shared_share)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "myref");
    {
	SV *	RETVAL;
	SV *	myref = ST(0)
;
#line 139 "forks.xs"
        if (!SvROK(myref))
            Perl_croak(aTHX_ "Argument to share needs to be passed as ref");
        myref = SvRV(myref);
        if(SvROK(myref))
            myref = SvRV(myref);

        Perl_sharedsv_share(aTHX_ myref);

        RETVAL = newRV_inc(myref);
#line 320 "forks.c"
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_threads__shared_lock); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_threads__shared_lock)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "myref");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	SV *	myref = ST(0)
;
#line 158 "forks.xs"
        int count;
        U32 process;
        U32 ordinal;
        AV *av_ord_lock;

        LEAVE;

        if (!SvROK(myref))
            Perl_croak(aTHX_ "Argument to lock needs to be passed as ref");
        myref = SvRV(myref);
        if(SvROK(myref))
            myref = SvRV(myref);

        ENTER;
        SAVETMPS;

        PUSHMARK(SP);
        XPUSHs(sv_2mortal(newSVpv("_lock",0)));
        XPUSHs(sv_2mortal(newRV_inc(myref)));
        PUTBACK;

        process = getpid();
        count = call_pv( "threads::shared::_remote",G_SCALAR );

        SPAGAIN;
        ordinal = POPl;
   /*     printf ("lock: ordinal = %d, process = %d\n",ordinal,process); */
        PUTBACK;

        FREETMPS;
        LEAVE;

        av_ord_lock = newAV();
        av_store(av_ord_lock, 1, newSVuv(process));
        av_store(av_ord_lock, 2, newSVuv(ordinal));

        SAVEDESTRUCTOR_X(exec_leave,newRV((SV*)av_ord_lock));
        ENTER;
#line 378 "forks.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_threads__shared_cond_wait); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_threads__shared_cond_wait)
{
    dVAR; dXSARGS;
    if (items < 1 || items > 2)
       croak_xs_usage(cv,  "myref, myref2= 0");
    {
	SV *	myref = ST(0)
;
	SV *	myref2;

	if (items < 2)
	    myref2 = 0;
	else {
	    myref2 = ST(1)
;
	}
#line 205 "forks.xs"
        if (!SvROK(myref))
            Perl_croak(aTHX_ "Argument to cond_wait needs to be passed as ref");
        myref = SvRV(myref);
        if(SvROK(myref))
            myref = SvRV(myref);

        ENTER;
        SAVETMPS;

        PUSHMARK(SP);
        XPUSHs(sv_2mortal(newSVpv("_wait",0)));
        XPUSHs(sv_2mortal(newRV_inc(myref)));
        if (myref2 && myref != myref2)
        {
            if (!SvROK(myref2))
                Perl_croak(aTHX_ "cond_wait lock needs to be passed as ref");
            myref2 = SvRV(myref2);
            if(SvROK(myref2))
                myref2 = SvRV(myref2);
            XPUSHs(sv_2mortal(newRV_inc(myref2)));
        }
        PUTBACK;

        call_pv( "threads::shared::_remote",G_DISCARD );

        FREETMPS;
        LEAVE;
#line 430 "forks.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_threads__shared_cond_timedwait); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_threads__shared_cond_timedwait)
{
    dVAR; dXSARGS;
    if (items < 2 || items > 3)
       croak_xs_usage(cv,  "myref, epochts, myref2= 0");
    {
#line 242 "forks.xs"
        int count;
        bool retval;
        U32 ordinal;
#line 447 "forks.c"
	int	RETVAL;
	dXSTARG;
	SV *	myref = ST(0)
;
	double	epochts = (double)SvNV(ST(1))
;
	SV *	myref2;

	if (items < 3)
	    myref2 = 0;
	else {
	    myref2 = ST(2)
;
	}
#line 246 "forks.xs"
        if (!SvROK(myref))
            Perl_croak(aTHX_ "Argument to cond_timedwait needs to be passed as ref");
        myref = SvRV(myref);
        if(SvROK(myref))
            myref = SvRV(myref);

        ENTER;
        SAVETMPS;

        PUSHMARK(SP);
        XPUSHs(sv_2mortal(newSVpv("_timedwait",0)));
        XPUSHs(sv_2mortal(newRV_inc(myref)));
        XPUSHs(sv_2mortal(newSVnv(epochts)));
        if (myref2 && myref != myref2)
        {
            if (!SvROK(myref2))
                Perl_croak(aTHX_ "cond_timedwait lock needs to be passed as ref");
            myref2 = SvRV(myref2);
            if(SvROK(myref2))
                myref2 = SvRV(myref2);
            XPUSHs(sv_2mortal(newRV_inc(myref2)));
        }
        PUTBACK;

        count = call_pv( "threads::shared::_remote",G_ARRAY );

        SPAGAIN;
        if (count != 2)
            croak ("Error receiving response value from _remote\n");

        retval = POPi;
        ordinal = POPi;
        PUTBACK;

        FREETMPS;
        LEAVE;
        RETVAL = retval;
        if (RETVAL == 0)
            XSRETURN_UNDEF;
#line 502 "forks.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_threads__shared_cond_signal); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_threads__shared_cond_signal)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "myref");
    {
	SV *	myref = ST(0)
;
#line 295 "forks.xs"
        if (!SvROK(myref))
            Perl_croak(aTHX_ "Argument to cond_signal needs to be passed as ref");
        myref = SvRV(myref);
        if(SvROK(myref))
            myref = SvRV(myref);

        ENTER;
        SAVETMPS;

        PUSHMARK(SP);
        XPUSHs(sv_2mortal(newSVpv("_signal",0)));
        XPUSHs(sv_2mortal(newRV_inc(myref)));
        PUTBACK;

        call_pv( "threads::shared::_remote",G_DISCARD );

        FREETMPS;
        LEAVE;
#line 537 "forks.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_threads__shared_cond_broadcast); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_threads__shared_cond_broadcast)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "myref");
    {
	SV *	myref = ST(0)
;
#line 321 "forks.xs"
        if (!SvROK(myref))
            Perl_croak(aTHX_ "Argument to cond_broadcast needs to be passed as ref");
        myref = SvRV(myref);
        if(SvROK(myref))
            myref = SvRV(myref);

        ENTER;
        SAVETMPS;

        PUSHMARK(SP);
        XPUSHs(sv_2mortal(newSVpv("_broadcast",0)));
        XPUSHs(sv_2mortal(newRV_inc(myref)));
        PUTBACK;

        call_pv( "threads::shared::_remote",G_DISCARD );

        FREETMPS;
        LEAVE;
#line 571 "forks.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_threads__shared_bless); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_threads__shared_bless)
{
    dVAR; dXSARGS;
    if (items < 1)
       croak_xs_usage(cv,  "myref, ...");
    {
#line 348 "forks.xs"
        HV* stash;
        SV* classname;
        STRLEN len;
        char *ptr;
        SV* myref2;
#line 590 "forks.c"
	SV *	myref = ST(0)
;
#line 354 "forks.xs"
        if (items == 1) {
            stash = CopSTASH(PL_curcop);
        } else {
            classname = ST(1);

            if (classname &&
                ! SvGMAGICAL(classname) &&
                ! SvAMAGIC(classname) &&
                SvROK(classname))
            {
                Perl_croak(aTHX_ "Attempt to bless into a reference");
            }
            ptr = SvPV(classname, len);
            if (ckWARN(WARN_MISC) && len == 0) {
                Perl_warner(aTHX_ packWARN(WARN_MISC),
                        "Explicit blessing to '' (assuming package main)");
            }
            stash = gv_stashpvn(ptr, len, TRUE);
        }
        SvREFCNT_inc(myref);
        (void)sv_bless(myref, stash);
        ST(0) = sv_2mortal(myref);

        myref2 = SvRV(myref);
        if(SvROK(myref2)) {
            myref2 = SvRV(myref2);
        }

        ENTER;
        SAVETMPS;

        PUSHMARK(SP);
        XPUSHs(sv_2mortal(newRV(myref2)));
        XPUSHs(sv_2mortal(newSVpv(HvNAME(stash), 0)));
        PUTBACK;

        call_pv( "threads::shared::_bless",G_DISCARD );

        FREETMPS;
        LEAVE;
#line 634 "forks.c"
    }
    XSRETURN(1);
}


XS_EUPXS(XS_threads__shared__id); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_threads__shared__id)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "myref");
    {
#line 402 "forks.xs"
        UV retval;
#line 649 "forks.c"
	UV	RETVAL;
	dXSTARG;
	SV *	myref = ST(0)
;
#line 404 "forks.xs"
        if (!SvROK(myref))
            Perl_croak(aTHX_ "Argument to _id needs to be passed as ref");
        myref = SvRV(myref);
        SvGETMAGIC(myref);
        if(SvROK(myref))
            myref = SvRV(myref);

        ENTER;
        SAVETMPS;

        PUSHMARK(SP);
        XPUSHs(sv_2mortal(newRV_inc(myref)));
        PUTBACK;

        call_pv( "threads::shared::__id",G_SCALAR );

        SPAGAIN;

        retval = POPi;
        PUTBACK;

        FREETMPS;
        LEAVE;
        RETVAL = retval;
#line 679 "forks.c"
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS_EXTERNAL(boot_forks); /* prototype to pass -Wmissing-prototypes */
XS_EXTERNAL(boot_forks)
{
    dVAR; dXSARGS;
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#endif
    XS_VERSION_BOOTCHECK;

        newXS("threads::shared::__DEF_PL_sharehook", XS_threads__shared___DEF_PL_sharehook, file);
        newXS("threads::shared::_check_pl_signal_unsafe_flag", XS_threads__shared__check_pl_signal_unsafe_flag, file);
        (void)newXSproto_portable("threads::shared::share", XS_threads__shared_share, file, "\\[$@%]");
        (void)newXSproto_portable("threads::shared::lock", XS_threads__shared_lock, file, "\\[$@%]");
        (void)newXSproto_portable("threads::shared::cond_wait", XS_threads__shared_cond_wait, file, "\\[$@%];\\[$@%]");
        (void)newXSproto_portable("threads::shared::cond_timedwait", XS_threads__shared_cond_timedwait, file, "\\[$@%]$;\\[$@%]");
        (void)newXSproto_portable("threads::shared::cond_signal", XS_threads__shared_cond_signal, file, "\\[$@%]");
        (void)newXSproto_portable("threads::shared::cond_broadcast", XS_threads__shared_cond_broadcast, file, "\\[$@%]");
        (void)newXSproto_portable("threads::shared::bless", XS_threads__shared_bless, file, "$;$");
        (void)newXSproto_portable("threads::shared::_id", XS_threads__shared__id, file, "\\[$@%]");

    /* Initialisation Section */

#line 434 "forks.xs"
{
    MY_CXT_INIT;
    Perl_sharedsv_init(aTHX);
}

#line 724 "forks.c"

    /* End of Initialisation Section */

#if (PERL_REVISION == 5 && PERL_VERSION >= 9)
  if (PL_unitcheckav)
       call_list(PL_scopestack_ix, PL_unitcheckav);
#endif
    XSRETURN_YES;
}

